export function copy7DayPlan(plan) {
  let text = '📅 7-DAY PREPARATION PLAN\n\n'
  
  Object.entries(plan).forEach(([day, tasks]) => {
    text += `${day}\n`
    tasks.forEach(task => {
      text += `  • ${task}\n`
    })
    text += '\n'
  })
  
  navigator.clipboard.writeText(text)
}

export function copyRoundChecklist(checklist) {
  let text = '✅ ROUND-WISE PREPARATION CHECKLIST\n\n'
  
  Object.entries(checklist).forEach(([round, items]) => {
    text += `${round}\n`
    items.forEach(item => {
      text += `  □ ${item}\n`
    })
    text += '\n'
  })
  
  navigator.clipboard.writeText(text)
}

export function copy10Questions(questions) {
  let text = '💡 10 LIKELY INTERVIEW QUESTIONS\n\n'
  
  questions.forEach((question, idx) => {
    text += `${idx + 1}. ${question}\n\n`
  })
  
  navigator.clipboard.writeText(text)
}

export function downloadAsText(analysis) {
  let content = '═══════════════════════════════════════════\n'
  content += '   PLACEMENT READINESS ANALYSIS REPORT\n'
  content += '═══════════════════════════════════════════\n\n'
  
  // Header
  if (analysis.company) content += `Company: ${analysis.company}\n`
  if (analysis.role) content += `Role: ${analysis.role}\n`
  if (analysis.createdAt) {
    content += `Analyzed: ${new Date(analysis.createdAt).toLocaleString()}\n`
  }
  content += `Readiness Score: ${analysis.readinessScore}/100\n\n`
  
  // Skills
  content += '───────────────────────────────────────────\n'
  content += 'KEY SKILLS EXTRACTED\n'
  content += '───────────────────────────────────────────\n\n'
  Object.entries(analysis.extractedSkills).forEach(([category, skills]) => {
    content += `${category}:\n`
    skills.forEach(skill => {
      const confidence = analysis.skillConfidenceMap?.[skill] || 'practice'
      const icon = confidence === 'know' ? '✓' : '○'
      content += `  ${icon} ${skill}\n`
    })
    content += '\n'
  })
  
  // Checklist
  content += '───────────────────────────────────────────\n'
  content += 'ROUND-WISE PREPARATION CHECKLIST\n'
  content += '───────────────────────────────────────────\n\n'
  Object.entries(analysis.checklist).forEach(([round, items]) => {
    content += `${round}\n`
    items.forEach(item => {
      content += `  □ ${item}\n`
    })
    content += '\n'
  })
  
  // 7-Day Plan
  content += '───────────────────────────────────────────\n'
  content += '7-DAY PREPARATION PLAN\n'
  content += '───────────────────────────────────────────\n\n'
  Object.entries(analysis.plan).forEach(([day, tasks]) => {
    content += `${day}\n`
    tasks.forEach(task => {
      content += `  • ${task}\n`
    })
    content += '\n'
  })
  
  // Questions
  content += '───────────────────────────────────────────\n'
  content += '10 LIKELY INTERVIEW QUESTIONS\n'
  content += '───────────────────────────────────────────\n\n'
  analysis.questions.forEach((question, idx) => {
    content += `${idx + 1}. ${question}\n\n`
  })
  
  content += '═══════════════════════════════════════════\n'
  content += 'Generated by Placement Readiness Platform\n'
  content += '═══════════════════════════════════════════\n'
  
  // Create download
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  const filename = `${analysis.company || 'Analysis'}_${analysis.role || 'Report'}_${new Date().toISOString().split('T')[0]}.txt`
  a.download = filename.replace(/\s+/g, '_')
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
